___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# Keras Basics

Welcome to the section on deep learning! We'll be using Keras with a TensorFlow backend to perform our deep learning operations.

This means we should get familiar with some Keras fundamentals and basics!

## Imports

In [0]:
import numpy as np

In [0]:
pip install tensorflow

Python interpreter will be restarted.
  Attempting uninstall: MarkupSafe
    Found existing installation: MarkupSafe 2.0.1
    Not uninstalling markupsafe at /databricks/python3/lib/python3.9/site-packages, outside environment /local_disk0/.ephemeral_nfs/envs/pythonEnv-1adb3ce2-645b-43c1-be8a-42fdd93a390d
    Can't uninstall 'MarkupSafe'. No files were found to uninstall.
  Attempting uninstall: protobuf
    Found existing installation: protobuf 4.21.5
    Not uninstalling protobuf at /databricks/python3/lib/python3.9/site-packages, outside environment /local_disk0/.ephemeral_nfs/envs/pythonEnv-1adb3ce2-645b-43c1-be8a-42fdd93a390d
    Can't uninstall 'protobuf'. No files were found to uninstall.
Python interpreter will be restarted.


## Dataset

We will use the famous Iris Data set.
_____
More info on the data set:
https://en.wikipedia.org/wiki/Iris_flower_data_set

## Reading in the Data Set

We've already downloaded the dataset, its in this folder. So let's open it up.

In [0]:
from sklearn.datasets import load_iris

In [0]:
iris = load_iris()

In [0]:
type(iris)  # Bunch object from sklearn

Out[4]: sklearn.utils.Bunch

In [0]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [0]:
X = iris.data

In [0]:
X

Out[7]: array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
      

In [0]:
y = iris.target

In [0]:
y

Out[9]: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [0]:
from tensorflow.keras.utils import to_categorical

In [0]:
y = to_categorical(y)  # one hot encoindg target labels

In [0]:
y.shape

Out[12]: (150, 3)

In [0]:
y

Out[13]: array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
    

## Split the Data into Training and Test

Its time to split the data into a train/test set. Keep in mind, sometimes people like to split 3 ways, train/test/validation. We'll keep things simple for now. **Remember to check out the video explanation as to why we split and what all the parameters mean!**

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [0]:
X_train.shape

Out[16]: (100, 4)

In [0]:
X_test.shape

Out[17]: (50, 4)

In [0]:
y_train.shape

Out[18]: (100, 3)

In [0]:
y_test.shape

Out[19]: (50, 3)

## Standardizing the Data

Usually when using Neural Networks, you will get better performance when you standardize the data. Standardization just means normalizing the values to all fit between a certain range, like 0-1, or -1 to 1.

The scikit learn library also provides a nice function for this.

http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html

In [0]:
from sklearn.preprocessing import MinMaxScaler

In [0]:
scaler_object = MinMaxScaler()

In [0]:
scaler_object.fit(X_train)  # only fitting on training data; do not fit on whole data to prevent leakage!

Out[22]: MinMaxScaler()

In [0]:
scaled_X_train = scaler_object.transform(X_train)

In [0]:
scaled_X_test = scaler_object.transform(X_test)

Ok, now we have the data scaled!

In [0]:
X_train.max()

Out[25]: 7.7

In [0]:
scaled_X_train.max()

Out[26]: 1.0

In [0]:
X_train

Out[27]: array([[5.7, 2.9, 4.2, 1.3],
       [7.6, 3. , 6.6, 2.1],
       [5.6, 3. , 4.5, 1.5],
       [5.1, 3.5, 1.4, 0.2],
       [7.7, 2.8, 6.7, 2. ],
       [5.8, 2.7, 4.1, 1. ],
       [5.2, 3.4, 1.4, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [5.1, 3.8, 1.9, 0.4],
       [5. , 2. , 3.5, 1. ],
       [6.3, 2.7, 4.9, 1.8],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [5.6, 2.7, 4.2, 1.3],
       [5.1, 3.4, 1.5, 0.2],
       [5.7, 3. , 4.2, 1.2],
       [7.7, 3.8, 6.7, 2.2],
       [4.6, 3.2, 1.4, 0.2],
       [6.2, 2.9, 4.3, 1.3],
       [5.7, 2.5, 5. , 2. ],
       [5.5, 4.2, 1.4, 0.2],
       [6. , 3. , 4.8, 1.8],
       [5.8, 2.7, 5.1, 1.9],
       [6. , 2.2, 4. , 1. ],
       [5.4, 3. , 4.5, 1.5],
       [6.2, 3.4, 5.4, 2.3],
       [5.5, 2.3, 4. , 1.3],
       [5.4, 3.9, 1.7, 0.4],
       [5. , 2.3, 3.3, 1. ],
       [6.4, 2.7, 5.3, 1.9],
       [5. , 3.3, 1.4, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 2.4, 3.8, 1.1],
     

In [0]:
scaled_X_train

Out[28]: array([[0.41176471, 0.40909091, 0.55357143, 0.5       ],
       [0.97058824, 0.45454545, 0.98214286, 0.83333333],
       [0.38235294, 0.45454545, 0.60714286, 0.58333333],
       [0.23529412, 0.68181818, 0.05357143, 0.04166667],
       [1.        , 0.36363636, 1.        , 0.79166667],
       [0.44117647, 0.31818182, 0.53571429, 0.375     ],
       [0.26470588, 0.63636364, 0.05357143, 0.04166667],
       [0.20588235, 0.68181818, 0.03571429, 0.08333333],
       [0.23529412, 0.81818182, 0.14285714, 0.125     ],
       [0.20588235, 0.        , 0.42857143, 0.375     ],
       [0.58823529, 0.31818182, 0.67857143, 0.70833333],
       [0.14705882, 0.63636364, 0.14285714, 0.04166667],
       [0.20588235, 0.45454545, 0.08928571, 0.04166667],
       [0.23529412, 0.59090909, 0.10714286, 0.16666667],
       [0.38235294, 0.31818182, 0.55357143, 0.5       ],
       [0.23529412, 0.63636364, 0.07142857, 0.04166667],
       [0.41176471, 0.45454545, 0.55357143, 0.45833333],
       [1.        , 0.

## Building the Network with Keras

Let's build a simple neural network!

In [0]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [0]:
model = Sequential()
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [0]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 8)                 40        
                                                                 
 dense_1 (Dense)             (None, 8)                 72        
                                                                 
 dense_2 (Dense)             (None, 3)                 27        
                                                                 
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


## Fit (Train) the Model

In [0]:
# Play around with number of epochs as well!
model.fit(scaled_X_train,y_train,epochs=150, verbose=2)

Epoch 1/150
4/4 - 1s - loss: 1.2696 - accuracy: 0.1900 - 674ms/epoch - 169ms/step
Epoch 2/150
4/4 - 0s - loss: 1.2553 - accuracy: 0.2200 - 7ms/epoch - 2ms/step
Epoch 3/150
4/4 - 0s - loss: 1.2427 - accuracy: 0.2800 - 7ms/epoch - 2ms/step
Epoch 4/150
4/4 - 0s - loss: 1.2312 - accuracy: 0.3100 - 7ms/epoch - 2ms/step
Epoch 5/150
4/4 - 0s - loss: 1.2199 - accuracy: 0.3300 - 7ms/epoch - 2ms/step
Epoch 6/150
4/4 - 0s - loss: 1.2086 - accuracy: 0.3400 - 7ms/epoch - 2ms/step
Epoch 7/150
4/4 - 0s - loss: 1.1977 - accuracy: 0.3500 - 7ms/epoch - 2ms/step
Epoch 8/150
4/4 - 0s - loss: 1.1868 - accuracy: 0.3500 - 8ms/epoch - 2ms/step
Epoch 9/150
4/4 - 0s - loss: 1.1770 - accuracy: 0.3500 - 6ms/epoch - 2ms/step
Epoch 10/150
4/4 - 0s - loss: 1.1673 - accuracy: 0.3500 - 6ms/epoch - 2ms/step
Epoch 11/150
4/4 - 0s - loss: 1.1586 - accuracy: 0.3500 - 6ms/epoch - 2ms/step
Epoch 12/150
4/4 - 0s - loss: 1.1499 - accuracy: 0.3500 - 6ms/epoch - 2ms/step
Epoch 13/150
4/4 - 0s - loss: 1.1415 - accuracy: 0.3500 -

## Predicting New Unseen Data

Let's see how we did by predicting on **new data**. Remember, our model has **never** seen the test data that we scaled previously! This process is the exact same process you would use on totally brand new data. For example , a brand new bank note that you just analyzed .

In [0]:
scaled_X_test

Out[33]: array([[ 0.52941176,  0.36363636,  0.64285714,  0.45833333],
       [ 0.41176471,  0.81818182,  0.10714286,  0.08333333],
       [ 1.        ,  0.27272727,  1.03571429,  0.91666667],
       [ 0.5       ,  0.40909091,  0.60714286,  0.58333333],
       [ 0.73529412,  0.36363636,  0.66071429,  0.54166667],
       [ 0.32352941,  0.63636364,  0.07142857,  0.125     ],
       [ 0.38235294,  0.40909091,  0.44642857,  0.5       ],
       [ 0.76470588,  0.5       ,  0.71428571,  0.91666667],
       [ 0.55882353,  0.09090909,  0.60714286,  0.58333333],
       [ 0.44117647,  0.31818182,  0.5       ,  0.45833333],
       [ 0.64705882,  0.54545455,  0.71428571,  0.79166667],
       [ 0.14705882,  0.45454545,  0.05357143,  0.        ],
       [ 0.35294118,  0.68181818,  0.03571429,  0.04166667],
       [ 0.17647059,  0.5       ,  0.07142857,  0.        ],
       [ 0.23529412,  0.81818182,  0.07142857,  0.08333333],
       [ 0.58823529,  0.59090909,  0.64285714,  0.625     ],
       [ 0.6470

In [0]:
# Spits out probabilities by default.
model.predict(scaled_X_test)

2/2 [==============================] - 0s 2ms/step
Out[34]: array([[2.5963528e-02, 6.2587577e-01, 3.4816068e-01],
       [9.8313642e-01, 8.4752897e-03, 8.3882855e-03],
       [2.9278974e-04, 1.6823769e-01, 8.3146948e-01],
       [1.6507858e-02, 5.3092992e-01, 4.5256218e-01],
       [1.1537285e-02, 5.1504803e-01, 4.7341463e-01],
       [9.5830679e-01, 2.2819703e-02, 1.8873410e-02],
       [4.7253180e-02, 6.1799169e-01, 3.3475512e-01],
       [1.1627369e-03, 2.1130745e-01, 7.8752977e-01],
       [7.8290347e-03, 4.4616905e-01, 5.4600197e-01],
       [3.7477586e-02, 6.2517059e-01, 3.3735189e-01],
       [3.9151576e-03, 3.4269708e-01, 6.5338778e-01],
       [9.5209813e-01, 2.5367619e-02, 2.2534214e-02],
       [9.7924137e-01, 1.0321906e-02, 1.0436627e-02],
       [9.5866454e-01, 2.1769406e-02, 1.9566040e-02],
       [9.8618066e-01, 6.4843474e-03, 7.3349583e-03],
       [1.6738718e-02, 5.3309238e-01, 4.5016903e-01],
       [1.1959379e-03, 2.4121062e-01, 7.5759345e-01],
       [4.0523540e-02,

In [0]:
# model.predict_classes(scaled_X_test)
predictions = np.argmax(model.predict(scaled_X_test),axis=1)
predictions

2/2 [==============================] - 0s 2ms/step
Out[39]: array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2])

In [0]:
y_test = y_test.argmax(axis=1)

In [0]:
y_test

Out[40]: array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

# Evaluating Model Performance

So how well did we do? How do we actually measure "well". Is 95% accuracy good enough? It all depends on the situation. Also we need to take into account things like recall and precision. Make sure to watch the video discussion on classification evaluation before running this code!

In [0]:
model.metrics_names

['loss', 'acc']

In [0]:
model.evaluate(x=scaled_X_test,y=y_test)

50/50 [==============================] - 0s 2ms/step


[0.2843634402751923, 0.96]

In [0]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [0]:
predictions = model.predict_classes(scaled_X_test)

In [0]:
predictions

array([1, 0, 2, 1, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [0]:
y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [0]:
confusion_matrix(y_test,predictions)

Out[43]: array([[19,  0,  0],
       [ 0, 14,  1],
       [ 0,  1, 15]])

In [0]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.93      0.93      0.93        15
           2       0.94      0.94      0.94        16

    accuracy                           0.96        50
   macro avg       0.96      0.96      0.96        50
weighted avg       0.96      0.96      0.96        50



In [0]:
accuracy_score(y_test, predictions)

Out[47]: 0.96

## Saving and Loading Models

Now that we have a model trained, let's see how we can save and load it.

In [0]:
model.save('keras_iris_model.h5')

In [0]:
from keras.models import load_model

In [0]:
newmodel = load_model('keras_iris_model.h5')

In [0]:
newmodel.predict(X_test)

2/2 [==============================] - 0s 2ms/step
Out[52]: array([[2.31389213e-10, 1.38719697e-02, 9.86128032e-01],
       [8.83368075e-01, 5.89520298e-03, 1.10736743e-01],
       [3.32970554e-18, 2.97070874e-05, 9.99970257e-01],
       [6.31156793e-11, 5.46699995e-03, 9.94532943e-01],
       [8.67480133e-12, 3.39925080e-03, 9.96600747e-01],
       [5.64052761e-01, 2.25535035e-02, 4.13393825e-01],
       [7.87407028e-09, 2.00035349e-02, 9.79996443e-01],
       [6.73720816e-15, 1.22536047e-04, 9.99877453e-01],
       [3.64554524e-12, 1.67730951e-03, 9.98322666e-01],
       [2.58648925e-09, 1.78947225e-02, 9.82105315e-01],
       [2.37704035e-13, 6.64519786e-04, 9.99335468e-01],
       [9.37588155e-01, 8.75733607e-03, 5.36545031e-02],
       [9.68122244e-01, 1.69968756e-03, 3.01781353e-02],
       [9.33396876e-01, 9.25967563e-03, 5.73435761e-02],
       [9.85222578e-01, 8.40982189e-04, 1.39364759e-02],
       [3.64048861e-11, 4.88263648e-03, 9.95117366e-01],
       [3.61178364e-15, 1.95

Great job! You now know how to preprocess data, train a neural network, and evaluate its classification performance!